config/routes.rb
LockShop::Application.routes.draw do
  devise_for :users

  resources :cores

  resources :keytypes

  resources :keys

  resources :keyways

  get "home/index"

  root :to => "home#index"
end

app/models/core.rb
# LockShop - SFIC lock management
# Copyright (C) 2011  Jared Szechy
#
# LockShop is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# LockShop is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with LockShop.  If not, see <http://www.gnu.org/licenses/>.

class Core < ActiveRecord::Base
  belongs_to :keyway
  belongs_to :control, :class_name => "Key", :foreign_key => "control_id"
  belongs_to :change, :class_name => "Key", :foreign_key => "change_id"
end

app/controllers/cores_controller.rb
# LockShop - SFIC lock management
# Copyright (C) 2011  Jared Szechy
#
# LockShop is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# LockShop is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with LockShop.  If not, see <http://www.gnu.org/licenses/>.

class CoresController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /cores
  # GET /cores.xml
  def index
    @cores = Core.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cores }
    end
  end

  # GET /cores/1
  # GET /cores/1.xml
  def show
    @core = Core.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @core }
    end
  end

  # GET /cores/new
  # GET /cores/new.xml
  def new
    @core = Core.new
	@change = Key.find(:all, :conditions => { :keytype_id => ["4"] }, :order => "name")
	@control = Key.find(:all, :conditions => { :keytype_id => ["2"] }, :order => "name")
	@keyway = Keyway.find(:all, :order => "name")

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @core }
    end
  end

  # GET /cores/1/edit
  def edit
    @core = Core.find(params[:id])
	@change = Key.find(:all, :conditions => { :keytype_id => ["4"] }, :order => "name")
	@control = Key.find(:all, :conditions => { :keytype_id => ["2"] }, :order => "name")
	@keyway = Keyway.find(:all, :order => "name")
  end

  # POST /cores
  # POST /cores.xml
  def create
    @core = Core.new(params[:core])
	@change = Key.find(:all, :conditions => { :keytype_id => ["4"] }, :order => "name")
	@control = Key.find(:all, :conditions => { :keytype_id => ["2"] }, :order => "name")
	@keyway = Keyway.find(:all, :order => "name")

    respond_to do |format|
      if @core.save
        format.html { redirect_to(@core, :notice => 'Core was successfully created.') }
        format.xml  { render :xml => @core, :status => :created, :location => @core }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @core.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cores/1
  # PUT /cores/1.xml
  def update
    @core = Core.find(params[:id])
	@change = Key.find(:all, :conditions => { :keytype_id => ["4"] }, :order => "name")
	@control = Key.find(:all, :conditions => { :keytype_id => ["2"] }, :order => "name")
	@keyway = Keyway.find(:all, :order => "name")

    respond_to do |format|
      if @core.update_attributes(params[:core])
        format.html { redirect_to(@core, :notice => 'Core was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @core.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cores/1
  # DELETE /cores/1.xml
  def destroy
    @core = Core.find(params[:id])
    @core.destroy

    respond_to do |format|
      format.html { redirect_to(cores_url) }
      format.xml  { head :ok }
    end
  end
  
  def update_controls
    control = Key.find(:all, :conditions => { :keytype_id => ["2"], :keyway_id => params[:keyway_id] }, :order => "name")
    render :update do |page|
	  page.replace_html 'controls', :partial => 'controls', :object => control
	end
  end
end

app/helpers/cores_helper.rb
# LockShop - SFIC lock management
# Copyright (C) 2011  Jared Szechy
#
# LockShop is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# LockShop is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with LockShop.  If not, see <http://www.gnu.org/licenses/>.

module CoresHelper
end

app/views/cores/_form.html.erb
<%= form_for(@core) do |f| %>
  <% if @core.errors.any? %>
    <div class="alert-message block-message error">
      <h2><%= pluralize(@core.errors.count, "error") %> prohibited this core from being saved:</h2>

      <ul>
      <% @core.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :name %>
	<div class="input">
		<%= f.text_field :name %>
	</div>
  </div>
  <div class="clearfix">
    <%= f.label :description %>
	<div class="input">
		<%= f.text_field :description %>
	</div>
  </div>
  <div class="clearfix">
    <%= f.label :marking %>
	<div class="input">
		<%= f.text_field :marking %>
	</div>
  </div>
  <div class="clearfix">
    <%= f.label :keyway %>
	<div class="input">
		<%= f.collection_select(:keyway_id, @keyway, :id, :name) %>
	</div>
  </div>
  <div class="clearfix">
    <%= f.label :change %>
	<div class="input">
		<%= f.collection_select(:change_id, @change, :id, :name) %>
	</div>
  </div>
  <div class="clearfix">
    <%= f.label :control %>
	<div class="input">
		<%= f.collection_select(:control_id, @control, :id, :name) %>
	</div>
  </div>
  <div class="actions">
	<button type="submit" class="btn primary">Save</button>
  </div>
<% end %>

app/views/cores/edit.html.erb
<section id="cores">
	<div class="page-header">
		<h1>Editing core</h1>
	</div>

	<%= render 'form' %>

	<%= link_to 'Show', @core %> |
	<%= link_to 'Back', cores_path %>
</section>

app/views/cores/index.html.erb
<section id="cores">
	<div class="page-header">
		<h1>Listing cores</h1>
	</div>

	<table>
	  <tr>
		<th>Name</th>
		<th>Description</th>
		<th>Marking</th>
		<th>Change</th>
		<th>Control</th>
		<th>Keyway</th>
		<th></th>
		<th></th>
		<th></th>
	  </tr>

	<% @cores.each do |core| %>
	  <tr>
		<td><%= core.name %></td>
		<td><%= core.description %></td>
		<td><%= core.marking %></td>
		<td><%= link_to Key.find(core.change).marking, key_path(core.change) %></td>
		<td><%= link_to Key.find(core.control).name, key_path(core.control) %></td>
		<td><%= Keyway.find(core.keyway).name %></td>
		<td><%= link_to 'Show', core %></td>
		<td><%= link_to 'Edit', edit_core_path(core) %></td>
		<td><%= link_to 'Destroy', core, :confirm => 'Are you sure?', :method => :delete %></td>
	  </tr>
	<% end %>
	</table>

	<br />

	<%= link_to 'New Core', new_core_path %>
</section>

app/views/cores/new.html.erb
<section id="cores">
	<div class="page-header">
		<h1>New core</h1>
	</div>

	<%= render 'form' %>

	<%= link_to 'Back', cores_path %>
</section>

app/views/cores/show.html.erb
<section id="cores">
	<div class="page-header">
		<h1><%= @core.name %></h1>
	</div>
	
	<p id="notice"><%= notice %></p>

	<p>
	  <b>Description:</b>
	  <%= @core.description %>
	</p>

	<p>
	  <b>Marking:</b>
	  <%= @core.marking %>
	</p>

	<p>
	  <b>Change:</b>
	  <%= link_to Key.find(@core.change).marking, key_path(@core.change) %>
	</p>

	<p>
	  <b>Control:</b>
	  <%= link_to Key.find(@core.control).name, key_path(@core.control) %>
	</p>

	<p>
	  <b>Keyway:</b>
	  <%= Keyway.find(@core.keyway).name %>
	</p>


	<%= link_to 'Edit', edit_core_path(@core) %> |
	<%= link_to 'Back', cores_path %>
</section>