config/routes.rb
LockShop::Application.routes.draw do
  devise_for :users

  resources :cores

  resources :keytypes

  resources :keys

  resources :keyways

  get "home/index"

  root :to => "home#index"
end

app/controllers/home_controller.rb
# LockShop - SFIC lock management
# Copyright (C) 2011  Jared Szechy
#
# LockShop is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# LockShop is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with LockShop.  If not, see <http://www.gnu.org/licenses/>.

class HomeController < ApplicationController
  def index
  end

end

app/helpers/home_helper.rb
# LockShop - SFIC lock management
# Copyright (C) 2011  Jared Szechy
#
# LockShop is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# LockShop is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with LockShop.  If not, see <http://www.gnu.org/licenses/>.

module HomeHelper
end

app/views/home/index.html.erb
<div id="masthead">
  <div class="inner">
    <h1>Home</h1>
	<p>Select an action below.</p>
  </div>
</div>
<div class="quickstart">
  <div class="container">
    	
		<div class="row center">
			<div class="span4 columns"><div class="button"><%= link_to image_tag("core.png", :border=>0), cores_path %>Cores</div></div>
			<div class="span4 columns"><div class="button"><%= link_to image_tag("key.png", :border=>0), keys_path %>Keys</div></div>
			<div class="span4 columns"><div class="button"><%= link_to image_tag("keyway.png", :border=>0), keyways_path %>Keyways</div></div>
			<div class="span4 columns"><div class="button"><%= link_to image_tag("keytypes.png", :border=>0), keytypes_path %>Key Types</div></div>
		</div>
  </div>
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />